allow configure to be skipped

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -13,6 +13,14 @@ on:
         required: true
         type: string
 
+      environments:
+        description: |
+          An optional duplication of the environment names specified in the config input.
+          Specifying this will skip the Configure job and proceed directly to Plan.
+          Must be in sync with the config input for the workflow to proceed.
+        required: false
+        type: string
+
       default_branch:
         required: false
         type: string
@@ -53,6 +61,8 @@ jobs:
     runs-on: [self-hosted, Linux, AWS]
     timeout-minutes: 10
 
+    if: ${{ inputs.environments == '' }}
+
     steps:
       - id: parse
         uses: Brightspace/terraform-workflows/actions/configure/parse@v3
@@ -74,12 +84,40 @@ jobs:
 
     needs: configure
 
+    # configure is conditionally skipped depending on our inputs
+    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
+
     strategy:
       fail-fast: false
       matrix:
-        environment: ${{ fromJson(needs.configure.outputs.environments) }}
+        environment: ${{ fromJson(inputs.config).*.workspaces.*.environment }}
 
     steps:
+    # Potentionally duplicate work from configure, but easier to always
+    # reference this step instead of both steps.parse/needs.configure
+    # depending on which is populated
+    - id: parse
+      uses: Brightspace/terraform-workflows/actions/configure/parse@v3
+      with:
+        config: ${{ inputs.config }}
+        max_environments: 50
+
+    # If the user supplied inputs.environments as an optimization, we need to
+    # validate it is in sync with inputs.config
+    - if: ${{ inputs.environments != '' }}
+      name: 'Assert: Preconfigured environments match config'
+      shell: bash
+      run: |
+        ENVIRONMENTS=$(jq -cr 'sort_by(.)' <<< "${ENVIRONMENTS}")
+        PRECONFIGURED_ENVIRONMENTS=$(jq -cr 'sort_by(.)' <<< "${PRECONFIGURED_ENVIRONMENTS}")
+        if [ "${ENVIRONMENTS}" != "${PRECONFIGURED_ENVIRONMENTS}" ]; then
+          >&2 echo "The environments input is out of sync with the config input"
+          exit 1
+        fi
+      env:
+        ENVIRONMENTS: ${{ steps.parse.outputs.environments }}
+        PRECONFIGURED_ENVIRONMENTS: ${{ inputs.environments }}
+
     - uses: Brightspace/third-party-actions@actions/checkout
 
     - if: ${{ github.event_name != 'pull_request' }}
@@ -93,14 +131,14 @@ jobs:
       name: 'Extract artifacts'
       uses: Brightspace/s3-artifact-actions/extract@master
       with:
-        path: ${{ fromJson(needs.configure.outputs.config)[matrix.environment].workspace_path }}/.artifacts
+        path: ${{ fromJson(steps.parse.outputs.config)[matrix.environment].workspace_path }}/.artifacts
         artifacts_url: ${{ inputs.artifacts_url }}
 
     - id: plan
       uses: Brightspace/terraform-workflows/actions/plan@v3
       with:
         comment_plan: ${{ inputs.comment_plan }}
-        config: ${{ toJson(fromJson(needs.configure.outputs.config)[matrix.environment]) }}
+        config: ${{ toJson(fromJson(steps.parse.outputs.config)[matrix.environment]) }}
         terraform_version: ${{ inputs.terraform_version }}
         refresh_on_pr: ${{ inputs.refresh_on_pr }}
 
@@ -127,7 +165,7 @@ jobs:
         )
         echo "changed_env_${ENVIRONMENT_INDEX}=${ENVIRONMENT}" >> "${GITHUB_OUTPUT}"
       env:
-        ENVIRONMENTS: ${{ needs.configure.outputs.environments }}
+        ENVIRONMENTS: ${{ steps.parse.outputs.environments }}
         ENVIRONMENT: ${{ matrix.environment }}
 
     outputs:
@@ -187,9 +225,14 @@ jobs:
     runs-on: [self-hosted, Linux, AWS]
     timeout-minutes: ${{ inputs.apply_timeout }}
 
+    # We don't directly need configure, but need to make sure it didn't fail
     needs: [configure, plan]
 
-    if: ${{ github.event_name != 'pull_request' && toJson(needs.plan.outputs.*) != '[]' }}
+    # 1st line: configure is conditionally skipped depending on our inputs
+    # 2nd line: only run on merges when there's changes
+    if: |
+      always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
+      && github.event_name != 'pull_request' && toJson(needs.plan.outputs.*) != '[]'
 
     strategy:
       fail-fast: false
@@ -200,6 +243,11 @@ jobs:
     concurrency: ${{ matrix.environment }}
 
     steps:
+    - id: parse
+      uses: Brightspace/terraform-workflows/actions/configure/parse@v3
+      with:
+        config: ${{ inputs.config }}
+
     - uses: Brightspace/third-party-actions@actions/checkout
 
     - uses: Brightspace/terraform-workflows/actions/apply@v3
@@ -208,5 +256,5 @@ jobs:
           {
             "terraform_version": "${{ inputs.terraform_version }}",
             "environment": "${{ matrix.environment }}",
-            "workspace_path": "${{ fromJson(needs.configure.outputs.config)[matrix.environment].workspace_path }}"
+            "workspace_path": "${{ fromJson(steps.parse.outputs.config)[matrix.environment].workspace_path }}"
           }
